#include "libtest.h"
#include "libmino.h"

// The function `main` contents the detail of unit testing.
int main(void) {
    projection.tetromino.type = I_Block;
    assert_eq(projection.tetromino.type, 'I');
    
    projection.tetromino.dot.bits.x = 0;
    projection.tetromino.dot.bits.y = 0;
    projection.tetromino.direction = North;

    assert_eq(is_tetrominos_i(projection), 0);
    buf_tetrominos_i_open(projection);
    // line0 I _ _ _ _ _ ...
    // line1 I _ _ _ _ _ ...
    // line2 I _ _ _ _ _ ...
    // line3 I _ _ _ _ _ ...
    // line4 _ _ _ _ _ _ ...

    assert_eq(board.y_bits.line0.x_all, 0b1);
    assert_eq(board.y_bits.line1.x_all, 0b1);
    assert_eq(board.y_bits.line2.x_all, 0b1);
    assert_eq(board.y_bits.line3.x_all, 0b1);
    assert_ne(is_tetrominos_i(projection), 0);
    buf_tetrominos_i_close(projection);
    // line0 _ _ _ _ _ _ ...
    // line1 _ _ _ _ _ _ ...
    // line2 _ _ _ _ _ _ ...
    // line3 _ _ _ _ _ _ ...
    // line4 _ _ _ _ _ _ ...

    projection.tetromino.direction = East;

    assert_eq(board.y_bits.line0.x_all, 0b0);
    assert_eq(board.y_bits.line1.x_all, 0b0);
    assert_eq(board.y_bits.line2.x_all, 0b0);
    assert_eq(board.y_bits.line3.x_all, 0b0);
    assert_eq(is_tetrominos_i(projection), 0);
    buf_tetrominos_i_open(projection);
    // line0 I I I I _ _ ...
    // line1 _ _ _ _ _ _ ...
    // line2 _ _ _ _ _ _ ...
    // line3 _ _ _ _ _ _ ...
    // line4 _ _ _ _ _ _ ...

    assert_eq(board.y_bits.line0.x_all, 0b1111);
    assert_ne(is_tetrominos_i(projection), 0b0);
    buf_tetrominos_i_close(projection);
    // line0 _ _ _ _ _ _ ...
    // line1 _ _ _ _ _ _ ...
    // line2 _ _ _ _ _ _ ...
    // line3 _ _ _ _ _ _ ...
    // line4 _ _ _ _ _ _ ...

    projection.tetromino.dot.bits.y = 1;

    assert_eq(board.y_bits.line0.x_all, 0b0);
    assert_eq(is_tetrominos_i(projection), 0b0);
    buf_tetrominos_i_open(projection);
    // line0 _ _ _ _ _ _ ...
    // line1 I I I I _ _ ...
    // line2 _ _ _ _ _ _ ...
    // line3 _ _ _ _ _ _ ...
    // line4 _ _ _ _ _ _ ...

    assert_eq(board.y_bits.line1.x_all, 0b1111);
    assert_ne(is_tetrominos_i(projection), 0b0);
    buf_tetrominos_i_close(projection);
    // line0 _ _ _ _ _ _ ...
    // line1 _ _ _ _ _ _ ...
    // line2 _ _ _ _ _ _ ...
    // line3 _ _ _ _ _ _ ...
    // line4 _ _ _ _ _ _ ...

    projection.tetromino.direction = South;
    
    assert_eq(board.y_bits.line1.x_all, 0b0);
    assert_eq(is_tetrominos_i(projection), 0);
    buf_tetrominos_i_open(projection);
    // line0 _ _ _ _ _ _ ...
    // line1 I _ _ _ _ _ ...
    // line2 I _ _ _ _ _ ...
    // line3 I _ _ _ _ _ ...
    // line4 I _ _ _ _ _ ...

    assert_eq(board.y_bits.line0.x_all, 0b0);
    assert_eq(board.y_bits.line1.x_all, 0b1);
    assert_eq(board.y_bits.line2.x_all, 0b1);
    assert_eq(board.y_bits.line3.x_all, 0b1);
    assert_eq(board.y_bits.line4.x_all, 0b1);
    assert_ne(is_tetrominos_i(projection), 0);
    buf_tetrominos_i_close(projection);
    // line0 _ _ _ _ _ _ ...
    // line1 _ _ _ _ _ _ ...
    // line2 _ _ _ _ _ _ ...
    // line3 _ _ _ _ _ _ ...
    // line4 _ _ _ _ _ _ ...

    projection.tetromino.direction = West;

    assert_eq(board.y_bits.line1.x_all, 0b0);
    assert_eq(board.y_bits.line2.x_all, 0b0);
    assert_eq(board.y_bits.line3.x_all, 0b0);
    assert_eq(board.y_bits.line4.x_all, 0b0);
    assert_eq(is_tetrominos_i(projection), 0);
    buf_tetrominos_i_open(projection);
    // line0 _ _ _ _ _ _ ...
    // line1 I I I I _ _ ...
    // line2 _ _ _ _ _ _ ...
    // line3 _ _ _ _ _ _ ...
    // line4 _ _ _ _ _ _ ...

    assert_eq(board.y_bits.line1.x_all, 0b1111);
    assert_ne(is_tetrominos_i(projection), 0);
    assert_ne(is_tetrominos_i(projection), 0);
    buf_tetrominos_i_close(projection);
    // line0 _ _ _ _ _ _ ...
    // line1 _ _ _ _ _ _ ...
    // line2 _ _ _ _ _ _ ...
    // line3 _ _ _ _ _ _ ...
    // line4 _ _ _ _ _ _ ...

    projection.tetromino.dot.bits.x = 2;
    projection.tetromino.dot.bits.y = 2;
    assert_eq(board.y_bits.line1.x_all, 0b0);
    assert_eq(is_tetrominos_i(projection), 0);
    buf_tetrominos_i_open(projection);
    // line0 _ _ _ _ _ _ ...
    // line1 _ _ _ _ _ _ ...
    // line2 _ _ I I I I ...
    // line3 _ _ _ _ _ _ ...
    // line4 _ _ _ _ _ _ ...
    
    assert_eq(board.y_bits.line2.x_all, 0b111100);
    assert_ne(is_tetrominos_i(projection), 0);
    buf_tetrominos_i_close(projection);
    // line0 _ _ _ _ _ _ ...
    // line1 _ _ _ _ _ _ ...
    // line2 _ _ _ _ _ _ ...
    // line3 _ _ _ _ _ _ ...
    // line4 _ _ _ _ _ _ ...

    projection.tetromino.direction += 1;
    
    assert_eq(board.y_bits.line2.x_all, 0b0);
    assert_eq(is_tetrominos_i(projection), 0);
    buf_tetrominos_i_open(projection);
    // line0 _ _ _ _ _ _ ...
    // line1 _ _ _ _ _ _ ...
    // line2 _ _ _ _ _ _ ...
    // line3 _ _ I _ _ _ ...
    // line4 _ _ I _ _ _ ...
    // line5 _ _ I _ _ _ ...
    // line6 _ _ I _ _ _ ...

    assert_eq(board.y_bits.line0.x_all, 0b0);
    assert_eq(board.y_bits.line1.x_all, 0b0);
    assert_eq(board.y_bits.line2.x_all, 0b100);
    assert_eq(board.y_bits.line3.x_all, 0b100);
    assert_eq(board.y_bits.line4.x_all, 0b100);
    assert_eq(board.y_bits.line5.x_all, 0b100);
    return 0;
}
